name: Playwright Tests + Pages Report

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        
        steps:
          - name: checkout repo
            uses: actions/checkout@v5

          - name: setup Node
            uses: actions/setup-node@v5
            with:
                node-version: lts/*
            
          - name: Install dependencies
            run: npm ci

          - name: Install Playwright browsers
            run: npx playwright install --with-deps

          - name: Run Playwright tests
            run: npx playwright test --reporter=html

          - name: Setup Pages
            uses: actions/configure-pages@v5

          - name: Upload Pages artifact
            if: ${{ !cancelled() }}
            uses: actions/upload-pages-artifact@v3
            with:
                path: playwright-report/

          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4